/** Closed names only: no selectors, paths, review text, or renderer errors. */
export const DOCUMENT_REVIEW_CONDITIONS = [
  'capture-pty-start',
  'comment-text-insert',
  'renderer-reload',
  'renderer-destroyed',
  'capture-pty-ready',
  'capture-exact-bytes',
  'store-flush',
  'store-restart',
  'renderer-authority-revoked',
  'review mode did not open from its focused control',
  'rendered keyboard capture did not open a comment form',
  'rendered note badge did not project after comment submission',
  'rendered note badge did not remain available outside review mode',
  'rendered note badge did not reopen review mode and focus its comment',
  'existing comment retained ambiguous controls, excess height, or layered emphasis',
  'new comment did not join the pending review',
  'source view did not project the rendered anchor with accessible review semantics',
  'source line-number capture did not focus a line-specific comment form',
  'unique file edit did not move the source review marker',
  'unique file edit did not expose the prior review location',
  'closing the reviewed tab did not settle',
  'replacement renderer did not regain its workbench',
  'insert did not preserve the draft lifecycle',
  'delivery preview did not close before direct send',
  'delivered review remained projected in the document',
  'rendered review block or enabled review control was missing',
  'ambient review selection check',
  'fixture-open',
  'mode-selection',
  'mode-active',
  'rendered-block-focus',
  'rendered review left gutter geometry',
  'review composer focus geometry',
  'source inline review geometry',
  'review delivery control-row geometry',
  'source review marker activation',
  'source-line-capture',
  'destination selection action',
  'accessible destination selection did not bind the first terminal',
  'prepared body wait',
  'exact preview wait',
  'draft-comment-restored',
  'inline review comment restore',
  'review mode restore',
  'project-active',
  'project-activation',
  'project-focus',
  'control-activation',
  'control-focus',
  'keyboard-dispatch',
] as const

export type DocumentReviewCondition = (typeof DOCUMENT_REVIEW_CONDITIONS)[number]
export const DOCUMENT_REVIEW_CHECKPOINTS = DOCUMENT_REVIEW_CONDITIONS.map(
  (condition) => `document-review: ${condition}` as const,
)
