/* This file is generated by scripts/generate-gascity-supervisor-types.mts. Do not edit it by hand. */
/* Regenerate with: npm run generate:gascity-supervisor-types */

import type {
  SessionStructuredToolInput,
  SessionStructuredToolResult,
  SessionStructuredUploadedFile,
} from './generated-supervisor-tools'
export type {
  SessionStructuredToolInput,
  SessionStructuredToolResult,
  SessionStructuredUploadedFile,
}

export interface OutputTurn {
  readonly role: string
  readonly text: string
  readonly timestamp?: string
}

export interface PaginationInfo {
  readonly has_newer_messages?: boolean
  readonly has_older_messages: boolean
  readonly returned_message_count: number
  readonly total_compactions: number
  readonly total_message_count: number
  readonly truncated_before_message?: string
}

/**
 * Provider-normalized transcript block discriminated by its closed block type
 * vocabulary.
 */
export type SessionStructuredBlock =
  | SessionStructuredBlockText
  | SessionStructuredBlockThinking
  | SessionStructuredBlockToolUse
  | SessionStructuredBlockToolResult
  | SessionStructuredBlockInteraction
  | SessionStructuredBlockImage
  | SessionStructuredBlockUnknown

export interface SessionStructuredBlockImage {
  readonly file_path?: string
  readonly image_url?: string
  readonly mime_type?: string
  readonly text?: string
  readonly type: 'image'
}

export interface SessionStructuredBlockInteraction {
  readonly interaction?: SessionStructuredInteraction
  readonly type: 'interaction'
}

export interface SessionStructuredBlockText {
  readonly text?: string
  readonly type: 'text'
}

export interface SessionStructuredBlockThinking {
  readonly signature?: string
  readonly thinking?: string
  readonly type: 'thinking'
}

export interface SessionStructuredBlockToolResult {
  readonly content?: string
  readonly file_path?: string
  readonly is_error?: boolean
  readonly name?: string
  readonly structured?: SessionStructuredToolResult
  readonly tool_call_id?: string
  readonly type: 'tool_result'
}

export interface SessionStructuredBlockToolUse {
  readonly file_path?: string
  readonly id?: string
  readonly input?: SessionStructuredToolInput
  readonly name?: string
  readonly type: 'tool_use'
}

export interface SessionStructuredBlockUnknown {
  readonly content?: string
  readonly file_path?: string
  readonly id?: string
  readonly image_url?: string
  readonly input?: SessionStructuredToolInput
  readonly interaction?: SessionStructuredInteraction
  readonly is_error?: boolean
  readonly mime_type?: string
  readonly name?: string
  readonly signature?: string
  readonly structured?: SessionStructuredToolResult
  readonly text?: string
  readonly thinking?: string
  readonly tool_call_id?: string
  readonly type: 'unknown'
}

export interface SessionStructuredContinuity {
  readonly compaction_count?: number
  readonly has_branches?: boolean
  readonly note?: string
  readonly status: string
}

export interface SessionStructuredCursor {
  readonly after_entry_id?: string
  /** Opaque cursor for an exact structured REST-to-SSE handoff or SSE reconnect. */
  readonly resume_token: string
}

export interface SessionStructuredDiagnostic {
  readonly code: string
  readonly count?: number
  readonly message?: string
}

export interface SessionStructuredGeneration {
  readonly id: string
  readonly observed_at?: string
}

export interface SessionStructuredHistory {
  readonly continuity: SessionStructuredContinuity
  readonly cursor: SessionStructuredCursor
  readonly diagnostics?: readonly SessionStructuredDiagnostic[] | null
  readonly gc_session_id?: string
  readonly generation: SessionStructuredGeneration
  readonly logical_conversation_id?: string
  readonly provider_session_id?: string
  readonly tail_state: SessionStructuredTailState
  readonly transcript_stream_id: string
}

export interface SessionStructuredIDESelection {
  readonly text?: string
}

export interface SessionStructuredInteraction {
  readonly action?: string
  readonly kind?: string
  readonly options?: readonly string[] | null
  readonly prompt?: string
  readonly request_id?: string
  readonly state: string
}

/**
 * Provider-normalized transcript message discriminated by its closed role vocabulary.
 */
export type SessionStructuredMessage =
  | SessionStructuredMessageUnknown
  | SessionStructuredMessageUser
  | SessionStructuredMessageAssistant
  | SessionStructuredMessageSystem
  | SessionStructuredMessageTool

export interface SessionStructuredMessageAssistant {
  readonly blocks: readonly SessionStructuredBlock[]
  readonly id: string
  readonly model?: string
  readonly provider?: string
  readonly role: 'assistant'
  readonly status: 'unknown' | 'final' | 'partial' | 'superseded'
  readonly stop_reason?: string
  readonly timestamp?: string
  readonly usage?: SessionStructuredUsage
}

export interface SessionStructuredMessageSystem {
  readonly blocks: readonly SessionStructuredBlock[]
  readonly id: string
  readonly provider?: string
  readonly role: 'system'
  readonly status: 'unknown' | 'final' | 'partial' | 'superseded'
  readonly system_event?: SessionStructuredSystemEvent
  readonly timestamp?: string
}

export interface SessionStructuredMessageTool {
  readonly blocks: readonly SessionStructuredBlock[]
  readonly id: string
  readonly provider?: string
  readonly role: 'tool'
  readonly status: 'unknown' | 'final' | 'partial' | 'superseded'
  readonly timestamp?: string
}

export interface SessionStructuredMessageUnknown {
  readonly blocks: readonly SessionStructuredBlock[]
  readonly id: string
  readonly model?: string
  readonly provider?: string
  readonly role: 'unknown'
  readonly status: 'unknown' | 'final' | 'partial' | 'superseded'
  readonly stop_reason?: string
  readonly system_event?: SessionStructuredSystemEvent
  readonly timestamp?: string
  readonly usage?: SessionStructuredUsage
  readonly user_prompt?: SessionStructuredUserPrompt
}

export interface SessionStructuredMessageUser {
  readonly blocks: readonly SessionStructuredBlock[]
  readonly id: string
  readonly provider?: string
  readonly role: 'user'
  readonly status: 'unknown' | 'final' | 'partial' | 'superseded'
  readonly timestamp?: string
  readonly user_prompt?: SessionStructuredUserPrompt
}

export interface SessionStructuredSystemEvent {
  readonly category?: string
  readonly code?: string
  readonly kind?: string
  readonly message?: string
}

export interface SessionStructuredTailState {
  readonly activity: string
  readonly degraded?: boolean
  readonly degraded_reason?: string
  readonly last_entry_id?: string
  readonly open_tool_call_ids?: readonly string[] | null
  readonly pending_interaction_ids?: readonly string[] | null
}

export interface SessionStructuredUsage {
  readonly cache_creation_tokens?: number
  readonly cache_read_tokens?: number
  readonly context_percent?: number
  readonly context_used_tokens?: number
  readonly context_window_tokens?: number
  readonly input_tokens?: number
  readonly output_tokens?: number
  readonly reasoning_tokens?: number
}

export interface SessionStructuredUserPrompt {
  readonly opened_files?: readonly string[] | null
  readonly selections?: readonly SessionStructuredIDESelection[] | null
  readonly text?: string
  readonly uploaded_files?: readonly SessionStructuredUploadedFile[] | null
}

export interface SessionTranscriptConversationResponse {
  /** Conversation or text transcript format. */
  readonly format: 'conversation' | 'text'
  readonly id: string
  readonly pagination?: PaginationInfo
  /** Producing provider identifier (claude, codex, gemini, opencode, etc.). */
  readonly provider: string
  readonly template: string
  /** Conversation/text transcript turns. */
  readonly turns?: readonly OutputTurn[] | null
}

/**
 * Discriminated union of session transcript response shapes. Raw provider-native frames
 * are available only on the raw branch; structured responses contain only
 * provider-neutral typed data.
 */
export type SessionTranscriptGetResponse =
  SessionTranscriptConversationResponse | SessionTranscriptStructuredResponse

/** Provider-neutral structured transcript snapshot. */
export interface SessionTranscriptStructuredResponse {
  /** Structured provider-neutral transcript format. */
  readonly format: 'structured'
  /** Normalized worker-history envelope when format is structured. */
  readonly history: SessionStructuredHistory
  readonly id: string
  /** Always snapshot for a REST structured transcript. */
  readonly operation: 'snapshot'
  readonly pagination?: PaginationInfo
  /** Producing provider identifier (claude, codex, gemini, opencode, etc.). */
  readonly provider: string
  /** Structured session transcript schema version. */
  readonly schema_version: 'session.structured.v1'
  /** Provider-normalized structured messages. */
  readonly structured_messages: readonly SessionStructuredMessage[]
  readonly template: string
}
