/* This file is generated by scripts/generate-gascity-supervisor-types.mts. Do not edit it by hand. */
/* Regenerate with: npm run generate:gascity-supervisor-types */

import type {
  OutputTurn,
  PaginationInfo,
  SessionStructuredHistory,
  SessionStructuredMessage,
} from './generated-supervisor-transcript'
export type {
  OutputTurn,
  PaginationInfo,
  SessionStructuredHistory,
  SessionStructuredMessage,
}

/** Identity of the document these types were read from. */
export const GASCITY_SUPERVISOR_API_PROVENANCE = {
  title: 'Gas City Supervisor API',
  specVersion: '0.1.0',
  specSha256: 'f21d56b753b6a004197f3f3f631b676c11fc8bdf1718186c11f7bfc5024d79c3',
  defaultEndpoint: '127.0.0.1:8372',
  operations: [
    'health',
    'cities',
    'sessions',
    'cityPending',
    'sessionPending',
    'transcript',
    'sessionStream',
    'cityEvents',
    'respond',
    'submit',
  ],
} as const

/** The exact request line of every operation hvir may call. */
export const GASCITY_SUPERVISOR_OPERATIONS = {
  health: { method: 'GET', path: '/health' },
  cities: { method: 'GET', path: '/v0/cities' },
  sessions: { method: 'GET', path: '/v0/city/{cityName}/sessions' },
  cityPending: { method: 'GET', path: '/v0/city/{cityName}/pending' },
  sessionPending: { method: 'GET', path: '/v0/city/{cityName}/session/{id}/pending' },
  transcript: { method: 'GET', path: '/v0/city/{cityName}/session/{id}/transcript' },
  sessionStream: { method: 'GET', path: '/v0/city/{cityName}/session/{id}/stream' },
  cityEvents: { method: 'GET', path: '/v0/city/{cityName}/events/stream' },
  respond: { method: 'POST', path: '/v0/city/{cityName}/session/{id}/respond' },
  submit: { method: 'POST', path: '/v0/city/{cityName}/session/{id}/submit' },
} as const

export interface AsyncAcceptedBody {
  /**
   * City event-stream sequence captured before the async request was accepted. Pass
   * this value as after_seq to /v0/city/{cityName}/events/stream to receive the request
   * result without replaying unrelated historical backlog. A value of 0 can also mean
   * no event provider is configured or the event log is empty.
   */
  readonly event_cursor: string
  /**
   * Correlation ID. Watch the city event stream for request.result.session.create,
   * request.result.session.message, request.result.session.submit, or request.failed
   * with this request_id.
   */
  readonly request_id: string
  /** Async request status. */
  readonly status: string
}

export interface CityInfo {
  readonly error?: string
  readonly name: string
  readonly path: string
  readonly phases_completed?: readonly string[] | null
  readonly running: boolean
  readonly status?: string
}

export interface CityPendingEntry {
  /** Pending interaction kind (e.g. tool-approval, prompt-for-input). */
  readonly kind: string
  /** Pending interaction request ID. */
  readonly request_id: string
  /** Session ID awaiting a human decision. */
  readonly session_id: string
}

export interface ErrorDetail {
  /** Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
  readonly location?: string
  /** Error message text */
  readonly message?: string
  /** The value at the given location */
  readonly value?: unknown
}

export interface ErrorModel {
  /** Stable machine-readable error code (the final segment of the type URN). */
  readonly code?: string
  /** A human-readable explanation specific to this occurrence of the problem. */
  readonly detail?: string
  /** Optional list of individual error details */
  readonly errors?: readonly ErrorDetail[] | null
  /** A URI reference that identifies the specific occurrence of the problem. */
  readonly instance?: string
  /** HTTP status code */
  readonly status?: number
  /**
   * A short, human-readable summary of the problem type. This value should not change
   * between occurrences of the error.
   */
  readonly title?: string
  /** A URI reference to human-readable documentation for the error. */
  readonly type?: string
}

export interface HeartbeatEvent {
  /** ISO 8601 timestamp when the heartbeat was sent. */
  readonly timestamp: string
}

export interface ListBodyCityPendingEntry {
  /** The list of items. */
  readonly items: readonly CityPendingEntry[] | null
  /** Cursor for the next page of results. */
  readonly next_cursor?: string
  /** True when one or more backends failed and the list is incomplete. */
  readonly partial?: boolean
  /** Human-readable errors from backends that failed during aggregation. */
  readonly partial_errors?: readonly string[] | null
  /** Total number of items matching the query. */
  readonly total: number
}

export interface ListBodySessionResponse {
  /** The list of items. */
  readonly items: readonly SessionResponse[] | null
  /** Cursor for the next page of results. */
  readonly next_cursor?: string
  /** True when one or more backends failed and the list is incomplete. */
  readonly partial?: boolean
  /** Human-readable errors from backends that failed during aggregation. */
  readonly partial_errors?: readonly string[] | null
  /** Total number of items matching the query. */
  readonly total: number
}

export type NoPayload = Readonly<Record<string, unknown>>

export interface PendingInteraction {
  readonly kind: string
  readonly metadata?: Readonly<Record<string, string>>
  readonly options?: readonly string[] | null
  readonly prompt?: string
  readonly request_id: string
}

export interface SessionActivityEvent {
  /** Session activity state: 'idle' or 'in-turn'. */
  readonly activity: string
}

export interface SessionLifecyclePayload {
  /** Short human-readable reason. */
  readonly reason?: string
  /** Canonical session bead ID. Always present. */
  readonly session_id: string
  /** Session template name when known at the emission site. */
  readonly template?: string
}

export interface SessionPendingClearedEvent {
  /** Request ID of the interaction that was cleared. */
  readonly request_id: string
}

export interface SessionPendingResponse {
  readonly pending?: PendingInteraction
  readonly supported: boolean
}

export interface SessionRespondInputBody {
  /** Response action (e.g. allow, deny). */
  readonly action: string
  /** Optional response metadata. */
  readonly metadata?: Readonly<Record<string, string>>
  /** Pending interaction request ID (optional). */
  readonly request_id?: string
  /** Optional response text. */
  readonly text?: string
}

export interface SessionRespondOutputBody {
  /** Session ID. */
  readonly id: string
  /** Operation result. */
  readonly status: string
}

export interface SessionResponse {
  readonly active_bead?: string
  readonly activity?: string
  readonly agent_kind?: string
  readonly alias?: string
  readonly attached: boolean
  readonly configured_named_session?: boolean
  readonly context_pct?: number
  readonly context_window?: number
  readonly created_at: string
  readonly display_name?: string
  readonly id: string
  readonly kind?: string
  readonly last_active?: string
  readonly last_nudge_delivered_at?: string
  readonly last_output?: string
  readonly metadata?: Readonly<Record<string, string>>
  readonly model?: string
  readonly options?: Readonly<Record<string, string>>
  readonly pool?: string
  readonly provider: string
  readonly reason?: string
  readonly rig?: string
  readonly running: boolean
  readonly session_name: string
  readonly state: string
  readonly submission_capabilities?: SubmissionCapabilities
  readonly template: string
  readonly title: string
  readonly work_dir?: string
}

export interface SessionStreamMessageEvent {
  readonly format: string
  readonly id: string
  readonly pagination?: PaginationInfo
  /** Producing provider identifier (claude, codex, gemini, opencode, etc.). */
  readonly provider: string
  readonly template: string
  readonly turns: readonly OutputTurn[] | null
}

/**
 * Provider-neutral structured transcript update with explicit snapshot, upsert, or
 * reset application semantics.
 */
export interface SessionStreamStructuredMessageEvent {
  /** Always structured for this event. */
  readonly format: 'structured'
  /** Normalized worker-history envelope for this snapshot or stream batch. */
  readonly history: SessionStructuredHistory
  readonly id: string
  /**
   * How the client applies this structured frame: replace from a snapshot/reset or
   * merge an upsert.
   */
  readonly operation: 'snapshot' | 'upsert' | 'reset'
  readonly pagination?: PaginationInfo
  /** Producing provider identifier (claude, codex, gemini, opencode, etc.). */
  readonly provider: string
  /**
   * Present if and only if operation is reset; absent for snapshot and upsert.
   * Identifies why the reset replaced the client transcript.
   */
  readonly reset_reason?:
    'resume_invalid' | 'stream_changed' | 'cursor_invalidated' | 'history_rewritten'
  /** Structured session transcript schema version. */
  readonly schema_version: 'session.structured.v1'
  /** Provider-normalized structured messages. */
  readonly structured_messages: readonly SessionStructuredMessage[]
  readonly template: string
}

export interface SessionSubmitInputBody {
  /** Submit intent; empty defaults to "default". */
  readonly intent?: SubmitIntent
  /** Message text to submit. */
  readonly message: string
}

export interface SubmissionCapabilities {
  readonly supports_follow_up: boolean
  readonly supports_interrupt_now: boolean
}

/** Semantic delivery choice for a user message on a session submit request. */
export type SubmitIntent = 'default' | 'follow_up' | 'interrupt_now'

export interface SupervisorCitiesOutputBody {
  /** Managed cities with status info. */
  readonly items: readonly CityInfo[] | null
  /** Total count. */
  readonly total: number
}

export interface SupervisorHealthOutputBody {
  /**
   * Build identity (typically a short git commit hash, with "-dirty" suffix when built
   * from an unclean tree). Empty when unavailable.
   */
  readonly build_id?: string
  /** Cities currently running. */
  readonly cities_running: number
  /** Total managed cities. */
  readonly cities_total: number
  /**
   * SHA-256 hex digest of the first managed city's packs.lock contents, for single-city
   * deployments (mirrors the startup field's first-city semantics). Drift checkers
   * compare this against the committed lockfile copy. Omitted when no city is
   * registered, the city has no packs.lock, or the lockfile is unreadable (read error
   * logged server-side) — treat absence as unknown, not as proof there is no lockfile.
   */
  readonly packs_lock_sha256?: string
  /** First-city startup info for single-city deployments. */
  readonly startup?: SupervisorStartup
  /** Health status ("ok"). */
  readonly status: string
  /** Supervisor uptime in seconds. */
  readonly uptime_sec: number
  /** Supervisor version. */
  readonly version: string
}

export interface SupervisorStartup {
  /** Current phase (when not ready). */
  readonly phase?: string
  /** Phases completed so far. */
  readonly phases_completed?: readonly string[] | null
  /** True when the city is running. */
  readonly ready: boolean
}

export interface TypedEventStreamEnvelopeSessionCrashed {
  readonly actor: string
  readonly depends_on_step_ids?: readonly string[]
  readonly message?: string
  readonly payload: SessionLifecyclePayload
  readonly run_id?: string
  readonly run_store_ref?: string
  readonly seq: number
  readonly session_id?: string
  readonly step_id?: string
  readonly subject?: string
  readonly subject_store_ref?: string
  readonly ts: string
  readonly type: 'session.crashed'
  readonly workflow?: WorkflowEventProjection
}

export interface TypedEventStreamEnvelopeSessionIdleKilled {
  readonly actor: string
  readonly depends_on_step_ids?: readonly string[]
  readonly message?: string
  readonly payload: NoPayload
  readonly run_id?: string
  readonly run_store_ref?: string
  readonly seq: number
  readonly session_id?: string
  readonly step_id?: string
  readonly subject?: string
  readonly subject_store_ref?: string
  readonly ts: string
  readonly type: 'session.idle_killed'
  readonly workflow?: WorkflowEventProjection
}

export interface TypedEventStreamEnvelopeSessionQuarantined {
  readonly actor: string
  readonly depends_on_step_ids?: readonly string[]
  readonly message?: string
  readonly payload: NoPayload
  readonly run_id?: string
  readonly run_store_ref?: string
  readonly seq: number
  readonly session_id?: string
  readonly step_id?: string
  readonly subject?: string
  readonly subject_store_ref?: string
  readonly ts: string
  readonly type: 'session.quarantined'
  readonly workflow?: WorkflowEventProjection
}

export interface TypedEventStreamEnvelopeSessionStopped {
  readonly actor: string
  readonly depends_on_step_ids?: readonly string[]
  readonly message?: string
  readonly payload: SessionLifecyclePayload
  readonly run_id?: string
  readonly run_store_ref?: string
  readonly seq: number
  readonly session_id?: string
  readonly step_id?: string
  readonly subject?: string
  readonly subject_store_ref?: string
  readonly ts: string
  readonly type: 'session.stopped'
  readonly workflow?: WorkflowEventProjection
}

export interface TypedEventStreamEnvelopeSessionSuspended {
  readonly actor: string
  readonly depends_on_step_ids?: readonly string[]
  readonly message?: string
  readonly payload: NoPayload
  readonly run_id?: string
  readonly run_store_ref?: string
  readonly seq: number
  readonly session_id?: string
  readonly step_id?: string
  readonly subject?: string
  readonly subject_store_ref?: string
  readonly ts: string
  readonly type: 'session.suspended'
  readonly workflow?: WorkflowEventProjection
}

export interface TypedEventStreamEnvelopeSessionWoke {
  readonly actor: string
  readonly depends_on_step_ids?: readonly string[]
  readonly message?: string
  readonly payload: NoPayload
  readonly run_id?: string
  readonly run_store_ref?: string
  readonly seq: number
  readonly session_id?: string
  readonly step_id?: string
  readonly subject?: string
  readonly subject_store_ref?: string
  readonly ts: string
  readonly type: 'session.woke'
  readonly workflow?: WorkflowEventProjection
}

export interface WorkflowAttemptSummary {
  readonly active_attempt: number
  readonly attempt_count: number
  readonly max_attempts?: number
}

export interface WorkflowBeadResponse {
  readonly assignee?: string
  readonly attempt?: number
  readonly id: string
  readonly kind: string
  readonly logical_bead_id?: string
  readonly metadata: Readonly<Record<string, string>>
  readonly scope_ref?: string
  readonly status: string
  readonly step_ref?: string
  readonly title: string
}

export interface WorkflowEventProjection {
  readonly attempt_summary?: WorkflowAttemptSummary
  readonly bead: WorkflowBeadResponse
  readonly changed_fields: readonly string[] | null
  readonly event_seq: number
  readonly event_ts: string
  readonly event_type: string
  readonly logical_node_id: string
  readonly requires_resync?: boolean
  readonly root_bead_id: string
  readonly root_store_ref: string
  readonly scope_kind: string
  readonly scope_ref: string
  readonly type: string
  readonly watch_generation: string
  readonly workflow_id: string
  readonly workflow_seq: number
}
