/* This file is generated by scripts/generate-gascity-supervisor-types.mts. Do not edit it by hand. */
/* Regenerate with: npm run generate:gascity-supervisor-types */

export interface SessionStructuredArgument {
  readonly name: string
  readonly value: string
}

export interface SessionStructuredPatchHunk {
  readonly file_path?: string
  readonly lines?: readonly string[] | null
  readonly new_lines?: number
  readonly new_start?: number
  readonly old_lines?: number
  readonly old_start?: number
}

export interface SessionStructuredPlanStep {
  readonly status?: string
  readonly step?: string
}

export interface SessionStructuredQuestion {
  readonly header?: string
  readonly multi_select?: boolean
  readonly options?: readonly SessionStructuredQuestionOption[] | null
  readonly question?: string
}

export interface SessionStructuredQuestionOption {
  readonly description?: string
  readonly label?: string
}

export interface SessionStructuredSearchResultItem {
  readonly snippet?: string
  readonly title?: string
  readonly url?: string
}

export interface SessionStructuredTodoItem {
  readonly active_form?: string
  readonly content?: string
  readonly id?: string
  readonly priority?: string
  readonly status?: string
}

export interface SessionStructuredToolError {
  /**
   * Provider-neutral category: user_rejection, user_rejection_with_reason,
   * command_failure, file_error, validation_error, timeout, network_error, or unknown.
   */
  readonly category:
    | 'user_rejection'
    | 'user_rejection_with_reason'
    | 'command_failure'
    | 'file_error'
    | 'validation_error'
    | 'timeout'
    | 'network_error'
    | 'unknown'
  readonly message?: string
  readonly user_reason?: string
}

/** Provider-neutral tool input discriminated by its closed kind vocabulary. */
export type SessionStructuredToolInput =
  | SessionStructuredToolInputUnknown
  | SessionStructuredToolInputCommand
  | SessionStructuredToolInputStdin
  | SessionStructuredToolInputCode
  | SessionStructuredToolInputPatch
  | SessionStructuredToolInputWrite
  | SessionStructuredToolInputGlob
  | SessionStructuredToolInputFetch
  | SessionStructuredToolInputSearch
  | SessionStructuredToolInputFile
  | SessionStructuredToolInputTodo
  | SessionStructuredToolInputPlan
  | SessionStructuredToolInputQuestion
  | SessionStructuredToolInputTask
  | SessionStructuredToolInputText
  | SessionStructuredToolInputArguments

export interface SessionStructuredToolInputArguments {
  readonly arguments: readonly SessionStructuredArgument[]
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'arguments'
}

export interface SessionStructuredToolInputCode {
  readonly code: string
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'code'
  readonly language?: string
}

export interface SessionStructuredToolInputCommand {
  readonly arguments?: readonly SessionStructuredArgument[] | null
  readonly command: string
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'command'
}

export interface SessionStructuredToolInputFetch {
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'fetch'
  readonly prompt?: string
  readonly url?: string
}

export interface SessionStructuredToolInputFile {
  readonly command?: string
  readonly file_path: string
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'file'
  readonly language?: string
}

export interface SessionStructuredToolInputGlob {
  readonly arguments?: readonly SessionStructuredArgument[] | null
  readonly file_path?: string
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'glob'
  readonly pattern?: string
  readonly query?: string
}

export interface SessionStructuredToolInputPatch {
  readonly file_path?: string
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'patch'
  readonly language?: string
  readonly patch: string
}

export interface SessionStructuredToolInputPlan {
  readonly explanation?: string
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'plan'
  readonly plan?: string
  readonly steps?: readonly SessionStructuredPlanStep[] | null
}

export interface SessionStructuredToolInputQuestion {
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'question'
  readonly options?: readonly string[] | null
  readonly question?: string
}

export interface SessionStructuredToolInputSearch {
  readonly arguments?: readonly SessionStructuredArgument[] | null
  readonly command?: string
  readonly file_path?: string
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'search'
  readonly pattern?: string
  readonly query?: string
}

export interface SessionStructuredToolInputStdin {
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'stdin'
  readonly linked_command?: string
  readonly task_id?: string
  readonly text?: string
}

export interface SessionStructuredToolInputTask {
  readonly description?: string
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'task'
  readonly prompt?: string
  readonly task_id?: string
  readonly task_status?: string
  readonly task_type?: string
}

export interface SessionStructuredToolInputText {
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'text'
  readonly text: string
}

export interface SessionStructuredToolInputTodo {
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'todo'
  readonly todos?: readonly SessionStructuredTodoItem[] | null
}

export interface SessionStructuredToolInputUnknown {
  readonly arguments?: readonly SessionStructuredArgument[] | null
  readonly code?: string
  readonly command?: string
  readonly description?: string
  readonly explanation?: string
  readonly file_path?: string
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'unknown'
  readonly language?: string
  readonly linked_command?: string
  readonly options?: readonly string[] | null
  readonly patch?: string
  readonly pattern?: string
  readonly plan?: string
  readonly prompt?: string
  readonly query?: string
  readonly question?: string
  readonly steps?: readonly SessionStructuredPlanStep[] | null
  readonly task_id?: string
  readonly task_status?: string
  readonly task_type?: string
  readonly text?: string
  readonly todos?: readonly SessionStructuredTodoItem[] | null
  readonly url?: string
}

export interface SessionStructuredToolInputWrite {
  readonly file_path?: string
  /**
   * Provider-neutral input kind such as command, code, patch, glob, fetch, search,
   * file, arguments, or text.
   */
  readonly kind: 'write'
  readonly language?: string
  readonly text?: string
}

/** Provider-neutral tool result discriminated by its closed kind vocabulary. */
export type SessionStructuredToolResult =
  | SessionStructuredToolResultUnknown
  | SessionStructuredToolResultBash
  | SessionStructuredToolResultPython
  | SessionStructuredToolResultRead
  | SessionStructuredToolResultGlob
  | SessionStructuredToolResultGrep
  | SessionStructuredToolResultSearch
  | SessionStructuredToolResultFetch
  | SessionStructuredToolResultTodo
  | SessionStructuredToolResultPlan
  | SessionStructuredToolResultQuestion
  | SessionStructuredToolResultStdin
  | SessionStructuredToolResultTask
  | SessionStructuredToolResultWrite
  | SessionStructuredToolResultEdit
  | SessionStructuredToolResultText

export interface SessionStructuredToolResultBash {
  readonly command?: string
  readonly content?: string
  readonly error?: SessionStructuredToolError
  readonly exit_code?: number
  readonly interrupted?: boolean
  readonly is_image?: boolean
  readonly kind: 'bash'
  readonly num_lines?: number
  readonly stderr?: string
  readonly stderr_lines?: number
  readonly stdout?: string
  readonly stdout_lines?: number
  readonly task_id?: string
  readonly task_status?: string
  readonly text?: string
  readonly timestamp?: string
  readonly truncated?: boolean
}

export interface SessionStructuredToolResultEdit {
  readonly content?: string
  readonly error?: SessionStructuredToolError
  readonly file_path?: string
  readonly file_paths?: readonly string[] | null
  readonly kind: 'edit'
  readonly new_string?: string
  readonly old_string?: string
  readonly original_file?: string
  readonly patch?: string
  readonly patch_hunks?: readonly SessionStructuredPatchHunk[] | null
  readonly replace_all?: boolean
  readonly user_modified?: boolean
}

export interface SessionStructuredToolResultFetch {
  readonly bytes?: number
  readonly content?: string
  readonly duration_ms?: number
  readonly error?: SessionStructuredToolError
  readonly kind: 'fetch'
  readonly num_lines?: number
  readonly status_code?: number
  readonly status_text?: string
  readonly text?: string
  readonly url?: string
}

export interface SessionStructuredToolResultGlob {
  readonly content?: string
  readonly duration_ms?: number
  readonly error?: SessionStructuredToolError
  readonly filenames?: readonly string[] | null
  readonly kind: 'glob'
  readonly num_files?: number
  readonly num_lines?: number
  readonly truncated?: boolean
}

export interface SessionStructuredToolResultGrep {
  readonly applied_limit?: number
  readonly content?: string
  readonly counts?: readonly SessionStructuredArgument[] | null
  readonly duration_ms?: number
  readonly error?: SessionStructuredToolError
  readonly filenames?: readonly string[] | null
  readonly kind: 'grep'
  readonly mode?: string
  readonly num_files?: number
  readonly num_lines?: number
  readonly num_results?: number
  readonly query?: string
  readonly result_items?: readonly SessionStructuredSearchResultItem[] | null
}

export interface SessionStructuredToolResultPlan {
  readonly content?: string
  readonly error?: SessionStructuredToolError
  readonly explanation?: string
  readonly kind: 'plan'
  readonly plan?: string
  readonly steps?: readonly SessionStructuredPlanStep[] | null
  readonly text?: string
}

export interface SessionStructuredToolResultPython {
  readonly code?: string
  readonly error?: SessionStructuredToolError
  readonly exit_code?: number
  readonly interrupted?: boolean
  readonly is_image?: boolean
  readonly kind: 'python'
  readonly stderr?: string
  readonly stdout?: string
  readonly text?: string
  readonly truncated?: boolean
}

export interface SessionStructuredToolResultQuestion {
  readonly answer?: string
  readonly answers?: readonly SessionStructuredArgument[] | null
  readonly content?: string
  readonly error?: SessionStructuredToolError
  readonly kind: 'question'
  readonly options?: readonly string[] | null
  readonly question?: string
  readonly questions?: readonly SessionStructuredQuestion[] | null
  readonly text?: string
}

export interface SessionStructuredToolResultRead {
  readonly content?: string
  readonly error?: SessionStructuredToolError
  readonly file_path?: string
  readonly kind: 'read'
  readonly language?: string
  readonly num_lines?: number
  readonly start_line?: number
  readonly total_lines?: number
}

export interface SessionStructuredToolResultSearch {
  readonly applied_limit?: number
  readonly content?: string
  readonly counts?: readonly SessionStructuredArgument[] | null
  readonly duration_ms?: number
  readonly error?: SessionStructuredToolError
  readonly filenames?: readonly string[] | null
  readonly kind: 'search'
  readonly mode?: string
  readonly num_files?: number
  readonly num_lines?: number
  readonly num_results?: number
  readonly query?: string
  readonly result_items?: readonly SessionStructuredSearchResultItem[] | null
}

export interface SessionStructuredToolResultStdin {
  readonly content?: string
  readonly error?: SessionStructuredToolError
  readonly kind: 'stdin'
  readonly num_lines?: number
  readonly task_id?: string
  readonly text?: string
}

export interface SessionStructuredToolResultTask {
  readonly content?: string
  readonly description?: string
  readonly error?: SessionStructuredToolError
  readonly exit_code?: number
  readonly kind: 'task'
  readonly output?: string
  readonly stderr?: string
  readonly stdout?: string
  readonly task_id?: string
  readonly task_status?: string
  readonly task_type?: string
  readonly text?: string
  readonly total_duration_ms?: number
  readonly total_tokens?: number
  readonly total_tool_use_count?: number
}

export interface SessionStructuredToolResultText {
  readonly content?: string
  readonly error?: SessionStructuredToolError
  readonly kind: 'text'
  readonly text?: string
}

export interface SessionStructuredToolResultTodo {
  readonly content?: string
  readonly error?: SessionStructuredToolError
  readonly kind: 'todo'
  readonly new_todos?: readonly SessionStructuredTodoItem[] | null
  readonly old_todos?: readonly SessionStructuredTodoItem[] | null
  readonly text?: string
}

export interface SessionStructuredToolResultUnknown {
  readonly answer?: string
  readonly answers?: readonly SessionStructuredArgument[] | null
  readonly applied_limit?: number
  readonly bytes?: number
  readonly code?: string
  readonly command?: string
  readonly content?: string
  readonly counts?: readonly SessionStructuredArgument[] | null
  readonly description?: string
  readonly duration_ms?: number
  readonly error?: SessionStructuredToolError
  readonly exit_code?: number
  readonly explanation?: string
  readonly file_path?: string
  readonly file_paths?: readonly string[] | null
  readonly filenames?: readonly string[] | null
  readonly interrupted?: boolean
  readonly is_image?: boolean
  readonly kind: 'unknown'
  readonly language?: string
  readonly mode?: string
  readonly new_string?: string
  readonly new_todos?: readonly SessionStructuredTodoItem[] | null
  readonly num_files?: number
  readonly num_lines?: number
  readonly num_results?: number
  readonly old_string?: string
  readonly old_todos?: readonly SessionStructuredTodoItem[] | null
  readonly options?: readonly string[] | null
  readonly original_file?: string
  readonly output?: string
  readonly patch?: string
  readonly patch_hunks?: readonly SessionStructuredPatchHunk[] | null
  readonly plan?: string
  readonly query?: string
  readonly question?: string
  readonly questions?: readonly SessionStructuredQuestion[] | null
  readonly replace_all?: boolean
  readonly result_items?: readonly SessionStructuredSearchResultItem[] | null
  readonly start_line?: number
  readonly status_code?: number
  readonly status_text?: string
  readonly stderr?: string
  readonly stderr_lines?: number
  readonly stdout?: string
  readonly stdout_lines?: number
  readonly steps?: readonly SessionStructuredPlanStep[] | null
  readonly task_id?: string
  readonly task_status?: string
  readonly task_type?: string
  readonly text?: string
  readonly timestamp?: string
  readonly total_duration_ms?: number
  readonly total_lines?: number
  readonly total_tokens?: number
  readonly total_tool_use_count?: number
  readonly truncated?: boolean
  readonly url?: string
  readonly user_modified?: boolean
}

export interface SessionStructuredToolResultWrite {
  readonly content?: string
  readonly error?: SessionStructuredToolError
  readonly file_path?: string
  readonly file_paths?: readonly string[] | null
  readonly kind: 'write'
  readonly language?: string
  readonly num_lines?: number
  readonly patch?: string
  readonly patch_hunks?: readonly SessionStructuredPatchHunk[] | null
  readonly start_line?: number
  readonly text?: string
  readonly total_lines?: number
}

export interface SessionStructuredUploadedFile {
  readonly file_path?: string
  readonly mime_type?: string
  readonly original_name?: string
  readonly preview_url?: string
  readonly size?: string
}
